# Generated by Django 5.2 on 2025-04-05 07:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('company_name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('company_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емаил')),
                ('working_hours', models.TextField(blank=True, null=True, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кнпоки')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='footer/items', verbose_name='Иконка')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
                'ordering': ('order',),
            },
        ),
    ]
