# Generated by Django 5.2 on 2025-04-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='working_hours_en',
            field=models.TextField(blank=True, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='working_hours_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Режим работы'),
        ),
    ]
