# Generated by Django 5.2 on 2025-04-05 07:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название категории')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tovar', verbose_name='Главная картинка товара')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='tovar', verbose_name='Главная картинка товара')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='tovar', verbose_name='Главная картинка товара')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок товара')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок товара')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('price_ru', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('price_en', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('production', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производство')),
                ('production_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производство')),
                ('production_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производство')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('model_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('model_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('is_available', models.BooleanField(default=False, verbose_name='Наличие')),
                ('is_available_ru', models.BooleanField(default=False, verbose_name='Наличие')),
                ('is_available_en', models.BooleanField(default=False, verbose_name='Наличие')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
                ('color_ru', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
                ('color_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст характеристики')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='items.item')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристика',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название категории')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='items.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.subcategory'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='items.user')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.item')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'unique_together': {('cart', 'item')},
            },
        ),
    ]
